### ISSUE TITLE
Multicolor series on a polar chart

### ISSUE THREAD

**Issue by pawelfus** [blacklabel/multicolor_series#20]
Demo: http://jsfiddle.net/av87r7uo/157/

Plugin should check if axes are radial and change paths accordingly.

**Comment by morganfree** [comment]
Multicolor series module needs to be loaded after highcharts-more module is loaded.
Demo: http://jsfiddle.net/av87r7uo/163/

Related to [Highcharts-#5293](https://github.com/highcharts/highcharts/issues/5293). When the issue will be fixed in Highcharts, the order of loading scripts should does not matter.
